apiVersion: kustomize.config.k8s.io/v1beta1
kind: Kustomization

resources:
- base

patches:
- path: overlays/api-service-monitor-patch.yaml
  target:
    kind: ServiceMonitor
    name: flask-api-monitor