apiVersion: v1
kind: Secret
metadata:
  name: hostspace-secret
  namespace: hostspace
  annotations:
    kubernetes.io/service-account.name: default
type: Generic
data:
  cf_api_key: YWI1OTBkMWM1ZDMxMzk0MTZmZWYzZDE3M2FkNDI2N2E3NWE0MQ==
  