version: "3"
services:

  backend:
    build:
        context: . 
        dockerfile: backend.txt
    ports:
      - "5000:5000"
    networks:
      - my-app-network
  frontend:
    build:
        context: . 
        dockerfile: frontend.txt
    ports:
      - "8080:80"
    networks:
      - my-app-network

 
networks:
  my-app-network:

    

