apiVersion: kustomize.config.k8s.io/v1beta1
kind: Kustomization

resources:
- alertmanager-alertmanager.yaml
- alertmanager-networkPolicy.yaml
- alertmanager-podDisruptionBudget.yaml
- alertmanager-prometheusRule.yaml
- alertmanager-secret.yaml
- alertmanager-service.yaml
- alertmanager-serviceAccount.yaml
- alertmanager-serviceMonitor.yaml
- app-service-monitor.yaml
- grafana-config.yaml
- grafana-dashboardDatasources.yaml
- grafana-dashboardDefinitions.yaml
- grafana-dashboardSources.yaml
- grafana-deployment.yaml
- grafana-networkPolicy.yaml
- grafana-prometheusRule.yaml
- grafana-service.yaml
- grafana-serviceAccount.yaml
- grafana-serviceMonitor.yaml
- kubePrometheus-prometheusRule.yaml
- kubeStateMetrics-clusterRole.yaml
- kubeStateMetrics-clusterRoleBinding.yaml
- kubeStateMetrics-deployment.yaml
- kubeStateMetrics-networkPolicy.yaml
- kubeStateMetrics-prometheusRule.yaml
- kubeStateMetrics-service.yaml
- kubeStateMetrics-serviceAccount.yaml
- kubeStateMetrics-serviceMonitor.yaml
- kubernetesControlPlane-prometheusRule.yaml
- kubernetesControlPlane-serviceMonitorApiserver.yaml
- kubernetesControlPlane-serviceMonitorCoreDNS.yaml
- kubernetesControlPlane-serviceMonitorKubeControllerManager.yaml
- kubernetesControlPlane-serviceMonitorKubeScheduler.yaml
- kubernetesControlPlane-serviceMonitorKubelet.yaml
- prometheus-clusterRole.yaml
- prometheus-clusterRoleBinding.yaml
- prometheus-networkPolicy.yaml
- prometheus-podDisruptionBudget.yaml
- prometheus-prometheus.yaml
- prometheus-prometheusRule.yaml
- prometheus-roleBindingConfig.yaml
- prometheus-roleBindingSpecificNamespaces.yaml
- prometheus-roleConfig.yaml
- prometheus-roleSpecificNamespaces.yaml
- prometheus-service.yaml
- prometheus-serviceAccount.yaml
- prometheus-serviceMonitor.yaml
- prometheus-config.yaml