apiVersion: v1
kind: ConfigMap
metadata:
  name: prometheus-config
data:
  prometheus.yml: |
    global:
      scrape_interval: 15s

    scrape_configs:
      - job_name: 'flask-api'
        kubernetes_sd_configs:
          - role: endpoints
        relabel_configs:
          - source_labels: [__meta_kubernetes_service_label_app]
            action: keep
            regex: flask-api
        metric_relabel_configs:
          - source_labels: [__name__]
            target_label: __name__
            regex: http_requests_total
            action: keep
      - job_name: 'kube-state-metrics'
        static_configs:
          - targets: ['kube-state-metrics:80']

    alerting:
      alertmanagers:
        - static_configs:
            - targets:
                - alertmanager-main.monitoring.svc:9093