apiVersion: v1
kind: Service
metadata:
  name: api-service
  labels:
        app: flask-api
spec:
  selector:
    app: flask-api
  ports:
    - name: flask-api
      protocol: TCP
      port: 5000
      targetPort: 5000
  type: ClusterIP