apiVersion: apps/v1
kind: Deployment
metadata:
  name: flask-api
spec:
  replicas: 1
  template:
    spec:
      containers:
        - name: flask-api
          image: kennedyuche/flask-api:dev-v1.0.0
