FROM node:18-alpine as build

WORKDIR /web

ENV PATH /web/node_modules/.bin:$PATH

RUN npm install -g npm && \
    npm install -g @vue/cli @vue/cli-service @vue/cli-plugin-babel @vue/cli-plugin-eslint

COPY package.json /web/package.json

RUN npm install

COPY . /web

RUN npm run build

FROM nginx:stable-alpine as runtime

COPY --from=build /web/dist /usr/share/nginx/html
COPY --from=build /web/.env /usr/share/nginx/html
COPY --from=build /web/nginx.conf.template /etc/nginx/conf.d/default.conf.template

EXPOSE 80