name: build and deploy to gc

on:
  push:
    branches:
      - main

env:
  PROJECT_ID: '${{ secrets.GOOGLE_PROJECT }}'
  GAR_LOCATION: us-east1
  SERVICE: '${{ secrets.SERVICE_ACCOUNT }}'
  REGION: us-central1
jobs:
  build_and_deploy:
    runs-on: ubuntu-latest

    steps:
    - name: Checkout code
      uses: actions/checkout@v2
        
    - name: Set up Google Cloud SDK
      uses: google-github-actions/setup-gcloud@v0
      with:
        service_account_key: ${{ secrets.GCP_CREDENTIALS }}
        project_id:  ${{ secrets.GOOGLE_PROJECT }}
        export_default_credentials: true

    - name: Build and Push Docker Image
      run: |
           gcloud auth configure-docker us-east1-docker.pkg.dev
           docker-compose up- f action.yml -t "${{ env.GAR_LOCATION }}-docker.pkg.dev/${{ env.PROJECT_ID }}/${{ env.SERVICE }}:${{ github.sha }}" .
           docker push "${{ env.GAR_LOCATION }}-docker.pkg.dev/${{ env.PROJECT_ID }}/${{ env.SERVICE }}:${{ github.sha }}":latest


       
   
