name: build and deploy to gc

on:
  push:
    branches:
      - main

jobs:
  build_and_deploy:
    runs-on: ubuntu-latest

    steps:
    - name: Checkout code
      uses: actions/checkout@v2
        
    - name: Set up Google Cloud SDK
      uses: GoogleCloudPlatform/github-actions/setup-gcloud@v0
      with:
        service_account_key: ${{ secrets.SERVICE_ACCOUNT }}
        project_id:  ${{ secrets.GOOGLE_PROJECT }}
        export_default_credentials: true

    - name: Build and Push Docker Image
      env: ${{ secrets.GOOGLE_PROJECT }}
      run: |
           gcloud auth configure-docker
           docker compose build -t us-east1-docker.pkg.dev/reliable-proton-403504/hostspace/challenge:latest .
           docker push us-east1-docker.pkg.dev/reliable-proton-403504/hostspace/challenge:latest

    

       
   
